// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Web.Entities
{
    public partial class City
    {
        //public City()
        //{
        //    Employees = new HashSet<Employee>();
        //}

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string CityName { get; set; }
        public int? StateId { get; set; }

        [ForeignKey("StateId")]
        //[InverseProperty("Cities")]
        public virtual State? State { get; set; }
        //[InverseProperty("Cities")]
        //public virtual ICollection<Employee> Employees { get; set; }
    }
}