// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Web.Entities
{
    [Table("Employee")]
    public partial class Employee
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Gender { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string Mobile { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? JoiningDate { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string PassWord { get; set; }
        public int? StateId { get; set; }
        public int? CitiesId { get; set; }
        public int? ImageId { get; set; }

        [ForeignKey("CitiesId")]
        //[InverseProperty("Employees")]
        public virtual City? Cities { get; set; }
        [ForeignKey("ImageId")]
        //[InverseProperty("Employees")]
        public virtual Image? Image { get; set; }
        [ForeignKey("StateId")]
        //[InverseProperty("Employees")]
        public virtual State? State { get; set; }
    }
}